<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */


get_header();
?>

	<div id="primary" class="content-area">
		<main id="main" class="site-main">
    <div class="author-box">
      <header class="page-header">
        <?php
          the_archive_title( '<h1 class="page-title">', '</h1>' );
        ?>
      </header><!-- .page-header -->
      <?php if ( function_exists( 'wpsabox_author_box' ) ) echo wpsabox_author_box(); ?>
    </div>
    <div class="posts-wrap">
      <div class="other-posts">
        <?php if ( have_posts() ) {
          // Load posts loop.
          while ( have_posts() ) {
            the_post();
            get_template_part( 'template-parts/content/content', 'with-intro' );
          }
        } ?>
      </div>
    </div>

    <div class="pagination">
      <?php the_posts_pagination( array(
          'screen_reader_text' => ' ', 
          'prev_text'          => '',
          'next_text'          => '',
          'before_page_number' => '<span class="meta-nav screen-reader-text"></span>',
      ) ); ?>
    </div>

		</main><!-- .site-main -->
	</div><!-- .content-area -->

<?php
get_footer();