<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */


get_header();
?>

	<div id="primary" class="content-area">
		<main id="main" class="site-main">
    <div class="posts-wrap">
      <?php
      $paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
      // are we on page one?
      if(1 == $paged) {
        // loop through the first 6 posts ?>
        <div class="latest-posts">
          <?php 
          $latest_posts = new WP_Query( array(
            'posts_per_page' => 6
          ) );
          
          if ( $latest_posts->have_posts() ) {
            // Load posts loop.
            while ( $latest_posts->have_posts() ) {
              $latest_posts->the_post();
              get_template_part( 'template-parts/content/content' );
            } 
          } 
          ?>
        </div>
        <div class="other-posts">
          <?php
          $other_posts = new WP_Query( array(
            'offset' => 6,
            'posts_per_page' => 14
          ) );
          if ( $other_posts->have_posts() ) {
            // Load posts loop.
            while ( $other_posts->have_posts() ) {
              $other_posts->the_post();
              get_template_part( 'template-parts/content/content', 'with-intro' );
            }
          }
          ?>
        </div>
      <?php } else {
        if ( have_posts() ) {
          // Load posts loop.
          while ( have_posts() ) {
            the_post();
            get_template_part( 'template-parts/content/content', 'with-intro' );
          }
        }
      }
      ?>
    </div>

    <div class="pagination">
      <?php the_posts_pagination( array(
          'screen_reader_text' => ' ', 
          'prev_text'          => '',
          'next_text'          => '',
          'before_page_number' => '<span class="meta-nav screen-reader-text"></span>',
      ) ); ?>
    </div>

		</main><!-- .site-main -->
	</div><!-- .content-area -->

<?php
get_footer();